project:
  type: book
  output-dir: docs

book:
  title: "数据分析"
  reader-mode: true 
  author: "连玉君"
#  date: "`r format(Sys.time(), '%d %B, %Y')`"
  date: today
  date-format: iso  # https://quarto.org/docs/reference/dates.html
#  lang: zh  # 不要设置这个，会导致很多问题
  
  sidebar: 
    title: "<a href='/index.html'>DS</a>"  # !important, 否则主页链返回链接会出错
    logo: images/ds-book-logo-40.png
    logo-href: https://lianxhcn.github.io/ds/
    style: floating  #docked
    search: true
    tools:
      - icon: house-fill
        href: https://www.lianxh.cn
      - icon: camera-video-fill
        href: https://lianxh-class.cn/
      - icon: github
        href: https://github.com/lianxhcn/ds

  page-footer:
    center: |
      [www.lianxh.cn](https://www.lianxh.cn)
    right: |
      Support: <a href="https://quarto.org/">Quarto</a>
  favicon: images/ds-book-logo-40.png   # URL logo
  site-url: https://lianxhcn.github.io/ds/ # 主页地址, 否则点击右上角链接会乱码
  editor: source    # 始终采用源代码模式编辑

#----------------------- Chapters ---------------
  chapters:

    - index.qmd
#    - body/_home.qmd
    - body/00_intro.ipynb
    - part: "**基础配置**"
      chapters: 
        - body/01_00_coding_with_AI.ipynb
        - body/01_01_install_anaconda.ipynb
        - body/01_02_jupyter_notebook.ipynb
        - body/01_03_install_FAQs.ipynb
        - body/01_04_markdown.md
    - part: "**Python 基础**"
      chapters: 
        - body/02_py_00_intro.ipynb
        - body/02_py_01_grammer.ipynb
        - body/02_py_02_QuickReference.md
        - body/02_py_03_packages.md
        - body/02_py_04_import.md
        - body/02_py_05_OOP.ipynb
        - body/02_py_06_filepath.ipynb
        - body/03_py_01_numpy.ipynb
        - body/03_py_02_pandas.ipynb
        - body/03_py_03_matplotlib.ipynb
        - body/03_py_04_function.ipynb
        - body/03_py_05_class.ipynb
    - part: "**数据分析**"
      chapters: 
        - body/data_01_get_data.ipynb
        - body/data_01_readdata.ipynb
        - body/data_02_data_type.ipynb
        - body/data_02_get_data_GMD.ipynb
        - body/TS_SZ_index.ipynb 
        - body/web_01_intro.md
    - part: "**可视化**"
      chapters: 
        - body/graph_01_intro.ipynb
        - body/graph_dis_box_violin.ipynb
        - body/graph_dis_histogram.ipynb
        - body/graph_dis_kdensity.ipynb
    - part: "**线性回归**"
      chapters: 
        - body/regress_01_OLS.ipynb
        - body/regress_02_wage.ipynb
        - body/regress_03_binscatter.ipynb
        - body/regress_04_wage_prediction.ipynb
    - part: "**时间序列**"
      chapters: 
        - body/TS_asset_return.qmd
        - body/TS_man_weight.ipynb
        - body/TS_ARMA.ipynb
        - body/TS_FRED_US_unemploy_rate.ipynb
        - body/TS_GARCH_BYD.ipynb
    - part: "**机器学习**"
      chapters: 
        - body/test_AB_test.ipynb
        - body/ML-Naive-Bayes.ipynb
        - body/ML-Random-Forests.ipynb
        - body/ML-baggboost-lab.ipynb
        - body/ML-Support-Vector-Machines.ipynb
        - body/ML-svm-lab.ipynb
        - body/06.00-Figure-Code.ipynb
    - part: "**作业展示**"
      chapters: 
        - homework/pre/Dangdang_G7_01_data_clean.ipynb
        - homework/pre/Dangdang_G7_02_data_analysis.ipynb
        - homework/pre/G8_China_stock_analysis.ipynb
        - homework/pre/Stock_G4_01_data_crawler.ipynb
        - homework/pre/Stock_G4_02_data_cleaning.ipynb
        - homework/pre/Stock_G4_03_data_analysis.ipynb
        - homework/pre/_ex02_万诗晴.ipynb
        - homework/pre/_ex02_吴倩茵.ipynb
        - homework/pre/_ex02_朱少荣.ipynb
        - homework/pre/_ex02_黄伊姿.ipynb

format:
  html:
    toc: true
    toc-depth: 3  # 三级以上 sections 才伸缩
    theme: cosmo         # 可选：cosmo, flatly, litera, litera, yeti 等  主题模版
    linestretch: 1.6          # 行间距   1.7   
    fontsize: 11.5pt          # 字号
    number-sections: true     # 自动章节编号
    link-external-newwindow: true
    highlight: true         # 代码高亮
    highlight-style: atom-one  # 语法高亮, atom-one, breezy, github, tango, solarized-light
    code-fold: false              # （可选）代码默认不折叠
    code-line-numbers: false      # （可选）关闭行号
    code-overflow: wrap        # 控制长代码的换行
#    html-table-processing: none    
    css: styles.css
#    include-after-body: footer.html    # https://github.com/oscarbaruffa/BigBookofR
    callout-appearance: default        # 启用 callout 默认渲染样式
    md-extensions:
      - callout                       # 确保 markdown 支持 callout 块语法
    includes:
      after-body: _includes/counter.html   # 不蒜子网站总访问量计数器
editor: visual

# _quarto_yml refs
# https://github.com/hadley/r4ds/blob/main/_quarto.yml
# https://github.com/appliedepi/epiRhandbook_eng/
